import { defineStore } from 'pinia'

export const useModelStore = defineStore('models', {
  state: () => ({
    models: [
      {
        id: 1,
        name: 'GPT-4',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=1',
        tags: ['LLM', '对话', '生成'],
        description: 'OpenAI最新的大型语言模型，具有强大的理解和生成能力，支持多轮对话、代码生成、文本分析等多种任务。',
        type: '文本生成',
        contextLength: '128K',
        vendor: 'GLM',
        params: '1750B',
        releaseDate: '2023-03-14',
        inputType: '文本',
        supportInference: '是',
        summary: 'GPT-4是OpenAI发布的最新大型语言模型，具有卓越的理解和生成能力，支持多模态输入，在各种任务中表现出色。',
        detail: 'GPT-4是OpenAI在2023年3月发布的最新一代大型语言模型，相比GPT-3.5，GPT-4在多个方面都有显著提升：\n\n1. **更强的理解能力**：能够理解更复杂的指令和上下文\n2. **多模态支持**：支持文本和图像输入\n3. **更长的上下文**：支持32K/128K的上下文长度\n4. **更准确的输出**：在事实性和逻辑性方面表现更好\n5. **安全性提升**：更少的幻觉和偏见\n\nGPT-4适用于各种应用场景，包括内容创作、代码编写、数据分析、教育辅导等。',
        views: 12580,
        favorites: 3420,
        likes: 5678,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 2,
        name: 'Claude 3',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=2',
        tags: ['LLM', '分析', '推理'],
        description: 'Anthropic推出的新一代AI助手，擅长长文本处理、复杂推理和创意写作，注重安全性和透明度。',
        type: '文本生成',
        contextLength: '200K',
        vendor: 'GLM',
        params: 'Unknown',
        releaseDate: '2024-03-04',
        inputType: '文本',
        supportInference: '是',
        summary: 'Claude 3是Anthropic的最新一代AI模型，在长文本理解、复杂推理和安全性方面表现出色。',
        detail: 'Claude 3是Anthropic在2024年3月发布的最新AI模型系列，包括Claude 3 Haiku、Claude 3 Sonnet和Claude 3 Opus三个版本，性能依次递增。\n\n主要特性：\n\n1. **超长上下文**：Opus版本支持200K token的上下文长度\n2. **卓越推理能力**：在复杂推理任务中表现优异\n3. **安全可靠**：采用Constitutional AI方法训练，注重安全性\n4. **多模态能力**：支持图像和文本输入\n5. **视觉理解**：具有强大的图像分析能力\n\nClaude 3特别适合需要长文本处理、复杂推理和安全要求高的应用场景。',
        views: 9876,
        favorites: 2890,
        likes: 4523,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 3,
        name: 'Gemini Pro',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=3',
        tags: ['多模态', '视觉', '理解'],
        description: 'Google开发的多模态AI模型，支持文本、图像、视频等多种输入，具有强大的跨模态理解能力。',
        type: '图像理解',
        contextLength: '128K',
        vendor: 'GLM',
        params: 'Unknown',
        releaseDate: '2023-12-06',
        inputType: '多模态',
        supportInference: '是',
        summary: 'Gemini Pro是Google的多模态AI模型，支持文本、图像、视频等多种输入，具有强大的跨模态理解能力。',
        detail: 'Gemini Pro是Google在2023年12月发布的多模态AI模型，是Gemini系列的中端版本。\n\n主要特性：\n\n1. **多模态能力**：同时支持文本、图像、视频、音频输入\n2. **强大理解**：在视觉理解和跨模态推理方面表现出色\n3. **代码生成**：具有优秀的代码理解和生成能力\n4. **多语言支持**：支持100+语言\n5. **长上下文**：支持128K token的上下文长度\n\nGemini Pro适合需要多模态交互、视觉理解和代码生成的应用场景。',
        views: 7654,
        favorites: 1987,
        likes: 3210,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 4,
        name: 'Qwen',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=4',
        tags: ['中文', '多语言', '开源'],
        description: '阿里云推出的通义千问系列模型，在中文理解、代码生成、数学推理等方面表现优异。',
        type: '文本生成',
        contextLength: '128K',
        vendor: '阿里巴巴',
        params: '72B',
        releaseDate: '2023-12-01',
        inputType: '文本',
        supportInference: '是',
        summary: 'Qwen是阿里云推出的通义千问系列模型，在中文理解、代码生成、数学推理等方面表现优异。',
        detail: 'Qwen（通义千问）是阿里云在2023年推出的大型语言模型系列，包括Qwen-7B、Qwen-14B、Qwen-72B等多个版本。\n\n主要特性：\n\n1. **中文优化**：针对中文理解进行了专门优化\n2. **代码能力**：在代码生成和理解方面表现优异\n3. **数学推理**：具有强大的数学推理能力\n4. **长上下文**：支持128K token的上下文长度\n5. **开源可用**：部分版本开源，可本地部署\n\nQwen特别适合中文应用场景，以及需要代码和数学能力的应用。',
        views: 5432,
        favorites: 1432,
        likes: 2345,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 5,
        name: 'DeepSeek-V2',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=5',
        tags: ['开源', '推理', '部署'],
        description: '深度求索推出的开源大模型，在数学、代码、推理等方面表现出色，支持本地部署和微调。',
        type: '文本生成',
        contextLength: '128K',
        vendor: '深度求索',
        params: '236B',
        releaseDate: '2024-05-20',
        inputType: '文本',
        supportInference: '是',
        summary: 'DeepSeek-V2是深度求索推出的开源大模型，采用MoE架构，在数学、代码、推理等方面表现出色。',
        detail: 'DeepSeek-V2是深度求索在2024年5月发布的开源大模型，采用了创新的MoE（混合专家）架构。\n\n主要特性：\n\n1. **MoE架构**：采用236B参数的MoE架构，激活参数为21B\n2. **数学专长**：在数学推理方面表现突出\n3. **代码能力**：具有强大的代码生成和理解能力\n4. **开源免费**：完全开源，可自由使用和修改\n5. **本地部署**：支持本地部署和微调\n\nDeepSeek-V2特别适合需要高性能推理、数学和代码能力的应用场景。',
        views: 4321,
        favorites: 1234,
        likes: 2109,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 6,
        name: 'Qwen-VL',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=6',
        tags: ['视觉', '理解', '生成'],
        description: '阿里云的视觉语言大模型，支持图文对话、图像描述、视觉问答等任务。',
        type: '图像理解',
        contextLength: '8K',
        vendor: '阿里巴巴',
        params: 'Unknown',
        releaseDate: '2023-08-25',
        inputType: '多模态',
        supportInference: '是',
        summary: 'Qwen-VL是阿里云的视觉语言大模型，支持图文对话、图像描述、视觉问答等任务。',
        detail: 'Qwen-VL是阿里云在2023年8月发布的视觉语言大模型，是Qwen系列的多模态版本。\n\n主要特性：\n\n1. **视觉理解**：具有强大的图像理解和分析能力\n2. **图文对话**：支持自然流畅的图文对话\n3. **图像描述**：能够生成详细的图像描述\n4. **视觉问答**：支持基于图像的问答任务\n5. **中文优化**：针对中文场景进行了优化\n\nQwen-VL适合需要视觉理解和多模态交互的应用场景。',
        views: 3876,
        favorites: 987,
        likes: 1876,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 7,
        name: 'DALL-E 3',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=7',
        tags: ['图像', '生成', '创意'],
        description: 'OpenAI的图像生成模型，可以根据文本描述生成高质量、富有创意的图像作品。',
        type: '图像生成',
        contextLength: '4K',
        vendor: 'GLM',
        params: 'Unknown',
        releaseDate: '2023-10-02',
        inputType: '文本',
        supportInference: '是',
        summary: 'DALL-E 3是OpenAI的图像生成模型，可以根据文本描述生成高质量、富有创意的图像作品。',
        detail: 'DALL-E 3是OpenAI在2023年10月发布的最新图像生成模型，相比DALL-E 2有显著提升。\n\n主要特性：\n\n1. **高质量生成**：生成的图像质量更高，细节更丰富\n2. **文本理解**：对复杂文本指令的理解能力更强\n3. **创意能力**：能够生成更加富有创意和想象力的图像\n4. **安全可控**：具有更好的安全控制机制\n5. **易用性**：与ChatGPT无缝集成，使用更加便捷\n\nDALL-E 3适合各种图像生成和创意设计应用场景。',
        views: 6543,
        favorites: 1765,
        likes: 2987,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 8,
        name: 'Sora',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=8',
        tags: ['视频', '生成', '创意'],
        description: 'OpenAI的视频生成模型，能够根据文本描述生成高质量、连贯的短视频内容。',
        type: '视频生成',
        contextLength: '512K',
        vendor: 'GLM',
        params: 'Unknown',
        releaseDate: '2024-02-16',
        inputType: '文本',
        supportInference: '否',
        summary: 'Sora是OpenAI的视频生成模型，能够根据文本描述生成高质量、连贯的短视频内容。',
        detail: 'Sora是OpenAI在2024年2月发布的视频生成模型，代表了AI视频生成的重大突破。\n\n主要特性：\n\n1. **高质量视频**：可生成高达1080p的高质量视频\n2. **长达一分钟**：支持最长60秒的视频生成\n3. **复杂场景**：能够理解复杂的场景和角色\n4. **连贯性好**：生成的视频内容连贯，逻辑性强\n5. **物理准确**：对物理世界的理解和模拟较为准确\n\nSora适合各种视频创作、影视制作和教育应用场景。',
        views: 5432,
        favorites: 1543,
        likes: 2654,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 9,
        name: 'GLM-4',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=9',
        tags: ['LLM', '推理', '部署'],
        description: '智谱AI推出的新一代大模型，在长文本、多轮对话、复杂推理等方面表现优异。',
        type: '文本生成',
        contextLength: '128K',
        vendor: 'GLM',
        params: 'Unknown',
        releaseDate: '2024-03-18',
        inputType: '文本',
        supportInference: '是',
        summary: 'GLM-4是智谱AI推出的新一代大模型，在长文本、多轮对话、复杂推理等方面表现优异。',
        detail: 'GLM-4是智谱AI在2024年3月发布的最新一代大模型，相比GLM-3有显著提升。\n\n主要特性：\n\n1. **长文本能力**：支持128K token的超长上下文\n2. **多轮对话**：在多轮对话中保持良好的连贯性\n3. **复杂推理**：具有强大的复杂推理能力\n4. **多模态支持**：GLM-4V版本支持视觉理解\n5. **性能优异**：在各种基准测试中表现优秀\n\nGLM-4适合需要长文本处理、多轮对话和复杂推理的应用场景。',
        views: 4567,
        favorites: 1234,
        likes: 2145,
        isFavorited: false,
        isLiked: false
      },
      {
        id: 10,
        name: 'DeepSeek-MoE',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=10',
        tags: ['开源', 'MoE', '推理'],
        description: '深度求索的混合专家模型，采用MoE架构，在保持性能的同时大幅降低推理成本。',
        type: '文本生成',
        contextLength: '16K',
        vendor: '深度求索',
        params: '16B',
        releaseDate: '2024-01-05',
        inputType: '文本',
        supportInference: '是',
        summary: 'DeepSeek-MoE是深度求索的混合专家模型，采用MoE架构，在保持性能的同时大幅降低推理成本。',
        detail: 'DeepSeek-MoE是深度求索在2024年1月发布的混合专家模型，采用创新的MoE架构设计。\n\n主要特性：\n\n1. **高效MoE**：采用16B参数的MoE架构，激活参数仅2.8B\n2. **低成本推理**：推理成本显著降低\n3. **性能优异**：在多项基准测试中表现优秀\n4. **开源免费**：完全开源，可自由使用\n5. **易部署**：支持本地部署和微调\n\nDeepSeek-MoE适合需要高效推理和成本控制的应用场景。',
        views: 3456,
        favorites: 876,
        likes: 1723,
        isFavorited: false,
        isLiked: false
      }
    ],
    skills: [
      {
        id: 1,
        name: '智能客服',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=11',
        tags: ['对话', '服务', '自动化'],
        category: '服务',
        creator: '我',
        description: '基于大模型的智能客服系统，能够理解用户意图、快速响应问题、提供个性化服务，大幅提升客服效率。',
        views: 8765,
        favorites: 2134,
        likes: 3567,
        isFavorited: false,
        isLiked: false,
        isMine: true,
        status: 'published',
        version: '1.0'
      },
      {
        id: 2,
        name: '代码助手',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=12',
        tags: ['编程', '开发', '效率'],
        category: '研发',
        creator: '我',
        description: '智能代码补全和生成工具，支持多种编程语言，能够理解代码上下文，提供准确的代码建议和优化方案。',
        views: 7654,
        favorites: 1876,
        likes: 2987,
        isFavorited: false,
        isLiked: false,
        isMine: true,
        status: 'published',
        version: '1.1'
      },
      {
        id: 3,
        name: '内容创作',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=13',
        tags: ['写作', '创意', '营销'],
        category: '综合',
        creator: '内容团队',
        description: 'AI内容创作工具，支持文章生成、文案优化、创意构思等多种功能，帮助创作者提升内容产出效率和质量。',
        views: 6543,
        favorites: 1543,
        likes: 2543,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 4,
        name: '数据分析',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=14',
        tags: ['分析', '可视化', '洞察'],
        category: '研发',
        creator: '数据团队',
        description: '智能数据分析助手，能够自动识别数据模式、生成分析报告、创建可视化图表，让数据分析变得简单高效。',
        views: 5432,
        favorites: 1234,
        likes: 2134,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 5,
        name: '翻译助手',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=15',
        tags: ['翻译', '多语言', '沟通'],
        category: '服务',
        creator: '语言团队',
        description: '支持100+语言的实时翻译工具，能够保持原文语境和风格，提供高质量的翻译结果，助力跨语言沟通。',
        views: 4321,
        favorites: 987,
        likes: 1765,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 6,
        name: '图像生成',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=16',
        tags: ['图像', '生成', '创意'],
        category: '制造',
        creator: '视觉团队',
        description: '强大的AI图像生成工具，支持多种风格和艺术效果，能够根据文字描述快速生成高质量图像。',
        views: 9876,
        favorites: 2345,
        likes: 4123,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 7,
        name: '文档处理',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=17',
        tags: ['文档', '处理', '自动化'],
        category: '综合',
        creator: '文档团队',
        description: '智能文档处理工具，支持文档格式转换、内容提取、智能摘要等功能，提高文档处理效率。',
        views: 3456,
        favorites: 876,
        likes: 1543,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 8,
        name: '视频编辑',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=18',
        tags: ['视频', '编辑', '制造'],
        category: '制造',
        creator: '视频团队',
        description: 'AI视频编辑助手，支持智能剪辑、自动配乐、特效添加等功能，让视频制作更加简单高效。',
        views: 5432,
        favorites: 1321,
        likes: 2345,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 9,
        name: '智能问答',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=19',
        tags: ['问答', '知识', '综合'],
        category: '综合',
        creator: '知识团队',
        description: '基于知识库的智能问答系统，能够快速准确地回答各类问题，提供专业的知识咨询服务。',
        views: 6789,
        favorites: 1654,
        likes: 2987,
        isFavorited: false,
        isLiked: false,
        isMine: false,
        status: 'published',
        version: '1.0'
      },
      {
        id: 10,
        name: '项目管理',
        avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=20',
        tags: ['管理', '研发', '协作'],
        category: '研发',
        creator: '我',
        description: 'AI驱动的项目管理工具，支持智能排期、风险预警、资源优化等功能，提升团队协作效率。',
        views: 4567,
        favorites: 1098,
        likes: 1987,
        isFavorited: false,
        isLiked: false,
        isMine: true,
        status: 'published',
        version: '1.2'
      }
    ]
  }),
  actions: {
    getModelById(id) {
      return this.models.find(m => m.id === parseInt(id))
    },
    getSkillById(id) {
      return this.skills.find(s => s.id === parseInt(id))
    }
  }
})
